// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeternaExam.Data.DAL;

namespace PeternaExam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220128100743_CreateServiceTable")]
    partial class CreateServiceTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeternaExam.Data.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Info2")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fas fa-desktop",
                            Info = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.",
                            Info2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Title = "Sure Quique Menu"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fas fa-flask",
                            Info = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.",
                            Info2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Title = "Sure Quique Menu"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "far fa-credit-card",
                            Info = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.",
                            Info2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Title = "Sure Quique Menu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
